services:
  api:
    container_name: bot_api
    restart: always
    build: ./api
    ports:
      - "8010:8000"
    volumes:
      - .:/app/bot_api
    networks:
      - web_network

  chat_bot:
    container_name: chat_curator_bot
    restart: always
    build: ./chat_bot
    volumes:
      - .:/app/chat_bot
    networks:
      - web_network

  info_bot:
    container_name: information_bot
    restart: always
    build: ./info_bot
    volumes:
      - .:/app/info_bot
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
