services:
  api:
    container_name: bot_api
    build: .
    command: python src/api/main.py
    ports:
      - "8010:8000"
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - web_network

  chat_bot:
    container_name: chat_bot
    build: .
    command: python src/chat_bot/main.py
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - web_network

  info_bot:
    container_name: info_bot
    build: .
    command: python src/info_bot/main.py
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - web_network

  bot_redis:
    image: redis
    volumes:
      - bot_redis:/var/lib/bot_redis
    networks:
      - web_network

  postgresql:
    image: postgres:latest
    container_name: postgres_bot
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - web_network

volumes:
  bot_redis:
  postgres_data:


networks:
  web_network:
    driver: bridge
